// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_silah_live.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOqj9jbfffKXXzkXlHqqwUO998ErDh_4M',
    appId: '1:373457574991:web:e5fd18c3655977b3829e3a',
    messagingSenderId: '373457574991',
    projectId: 'silah-application',
    authDomain: 'silah-application.firebaseapp.com',
    storageBucket: 'silah-application.firebasestorage.app',
    measurementId: 'G-8B0BBEWLXQ',
  );

  /// Web FirebaseOptions (silah-application)

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm4rreirfZ6QMmVH4UhBIDd_mtsnPFlAo',
    appId: '1:373457574991:android:e265d593e892da8b829e3a',
    messagingSenderId: '373457574991',
    projectId: 'silah-application',
    storageBucket: 'silah-application.firebasestorage.app',
  );

  // Mobile FirebaseOptions (silah-application)

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_U6Xv8Usfq7LkfT-OfQ4eWJG0ju3myCM',
    appId: '1:373457574991:ios:463612783c06579e829e3a',
    messagingSenderId: '373457574991',
    projectId: 'silah-application',
    storageBucket: 'silah-application.firebasestorage.app',
    iosBundleId: 'com.appari.silah-application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOqj9jbfffKXXzkXlHqqwUO998ErDh_4M',
    appId: '1:373457574991:web:2de68530d07837c8829e3a',
    messagingSenderId: '373457574991',
    projectId: 'silah-application',
    authDomain: 'silah-application.firebaseapp.com',
    storageBucket: 'silah-application.firebasestorage.app',
    measurementId: 'G-CHBWNC4EJN',
  );

}