// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_silah_live.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web FirebaseOptions (silah-app-9acb6)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4DrEz2NzlvxFVPEulE_PXm9IYkfN-eYA',
    authDomain: 'silah-app-9acb6.firebaseapp.com',
    projectId: 'silah-app-9acb6',
    storageBucket: 'silah-app-9acb6.firebasestorage.app',
    messagingSenderId: '330197769102',
    appId: '1:330197769102:web:9f34f333b7d0bcd34de2df',
    measurementId: 'G-970DHKL9G1',
  );

  // Existing mobile configs (unchanged)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1eFcNEhxG4o7wh6LdqqkaR4qGq4l1bR4',
    appId: '1:292889484226:android:c406ebc97fef080fb4145b',
    messagingSenderId: '292889484226',
    projectId: 'silah-158eb',
    storageBucket: 'silah-158eb.firebasestorage.app',
  
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjRgAuTsdQJbX4Pn4xMPoWlI62atkdCrE',
    appId: '1:292889484226:ios:97bb9fd3b1a04681b4145b',
    messagingSenderId: '292889484226',
    projectId: 'silah-158eb',
    storageBucket: 'silah-158eb.firebasestorage.app',
    iosBundleId: 'com.example.silah_app',
  );
}
